import type en from './content.en.ts'

const zh: typeof en = {
  lang: 'zh-CN', language: 'English', languageHref: '../',
  title: 'DeepSeek Harness Themes — 让工作区，有你的风格',
  description: '为 DeepSeek Harness 带来 74 款 Design MD 风格主题。浏览真实配色，找到你的风格，通过原生插件机制轻松安装。',
  nav: ['主题集', '原生集成', '安装'], skip: '跳至正文',
  eyebrow: '一点个性，让工作区多一份喜欢。',
  headline: '你的工作区，<br>值得有<em>自己的风格。</em>',
  intro: '每天相处数小时的地方，也该合你的心意。为 DeepSeek Harness 换上 74 款精心生成的主题，从安静的中性色，到毫不掩饰的鲜明。',
  explore: '找到你的主题', github: '在 GitHub 查看',
  heroNote: '开源。一个插件。焕然一新的日常。',
  previewLabel: '交互配色预览', previewHint: '选一种配色，看看变化。',
  previewWorkspace: '个人工作区', previewSession: '换个视角，重新出发',
  previewQuestion: '一起做一个让人愿意停留的工作区吧。',
  previewAnswer: '少一点干扰，多一点专注。让每一次打开，都觉得这里属于自己。',
  previewTask: '重新想象你的工作区', previewTaskNote: '熟悉的能力，不一样的心情。',
  previewInput: '今天，想创造些什么？', previewDisclaimer: '模拟界面 · 真实主题配色',
  themeLoading: '正在加载主题配色…', themeError: '主题配色加载失败，请检查连接后重试。', retry: '重新加载',
  stats: [['74', '款各具个性的主题'], ['01', '个原生插件'], ['MIT', '开源许可']],
  collectionEyebrow: '01 / 寻找你的风格', collectionTitle: '挑一个，成为日常。',
  collectionIntro: '熟悉的设计语言，在 AI 工作区里重新表达。点击任意主题，在上方演示中体验它的配色。',
  search: '搜索主题', searchPlaceholder: '找找 Claude、Linear、Spotify…',
  filters: ['全部主题', '浅色', '深色'], categoryLabel: '分类', allCategories: '全部分类',
  count: '共 74 款，找到 {count} 款', selected: '正在预览', previewAction: '预览', light: '浅色', dark: '深色',
  emptyTitle: '还没找到合适的主题。', emptyText: '换个名字搜索，或清除筛选再看看。', reset: '清除筛选',
  showAll: '浏览全部 74 款主题', showLess: '收起主题', backPreview: '查看所选配色 ↑',
  nativeEyebrow: '02 / 原生集成', nativeTitle: '焕新外观，<br>还是熟悉的 Harness。',
  nativeIntro: 'Everything is a Plugin。主题也是。通过原生插件机制，让你的风格和日常使用的工具自然地融为一体。',
  features: [
    ['自然融入。', '通过 Harness 公开的 Theme Service 注册主题，并在设置中加入专属入口。熟悉的位置，多一种选择。'],
    ['选一次，一直喜欢。', '所选主题保存在插件自己的设置命名空间里。刷新页面，喜欢的风格依然在。'],
    ['轻量接入，尽情表达。', '使用原生插件管理器安装。无需修改 Harness 源码、替换文件或额外安装浏览器扩展。'],
  ],
  blog: '阅读项目故事：Everything is a Plugin',
  installEyebrow: '03 / 让喜欢成为日常', installTitle: '一条命令，<br>换一种打开方式。',
  installIntro: '已经在用 DeepSeek Harness？添加插件，启动 Web 界面，然后选一款你喜欢的主题。',
  stepInstall: '添加插件', stepLaunch: '启动 Harness', stepChoose: '选择你的主题',
  chooseText: '打开 Settings → Design MD themes，选中主题卡片。现在，这里更像你的工作区了。',
  copy: '复制', copied: '已复制！', copyFallback: '请选中下方命令，手动复制。', commandLabel: '安装命令',
  compatibility: '仓库记录的兼容版本：DeepSeek Harness 0.1.1-rc.2。本地构建要求：Node.js ^22.19.0 或 ≥24.0.0。',
  installDocs: '查看安装文档', faqTitle: '你可能还想知道。',
  faqs: [
    ['会修改我的 Harness 安装文件吗？', '插件使用 Harness 公开的扩展服务注册主题与设置入口，无需修改 Harness 源文件。'],
    ['在这里选主题，会改变我的应用吗？', '这里是交互配色预览。要在你的 Harness 中启用主题，请先安装插件，再到 Settings → Design MD themes 中选择。'],
    ['74 款主题来自哪里？', '来自 VoltAgent 的 awesome-design-md 固定版本快照，经过归一化后生成 Harness 主题 token。品牌名称仅标识设计灵感，不代表官方合作。'],
    ['可以免费使用吗？', '可以。本项目以 MIT 许可证开源。许可证、素材来源及第三方声明均可在 GitHub 仓库中查看。'],
  ],
  footerTitle: '让工作区，有你的风格。', footerNote: '为 DeepSeek Harness 制作的独立主题集。',
  attribution: '设计灵感来自 VoltAgent / awesome-design-md。品牌名称仅标识风格来源，不代表任何关联或背书。',
  source: '源代码', license: 'MIT 许可证', notices: '来源声明',
  noScript: '启用 JavaScript 后可使用交互主题集。你仍可阅读下方安装说明并访问相关链接。',
}
export default zh
