export default {
  lang: 'en', language: '中文', languageHref: 'zh/',
  title: 'DeepSeek Harness Themes — Make your workspace feel like yours',
  description: '74 Design MD-inspired themes for DeepSeek Harness. Explore real color palettes, find your style, and install through the native plugin system.',
  nav: ['The collection', 'How it works', 'Install'], skip: 'Skip to content',
  eyebrow: 'A LITTLE PERSONALITY. A BETTER WORKSPACE.',
  headline: 'Your workspace.<br>Your <em>kind of beautiful.</em>',
  intro: 'You spend hours here. Make it feel like you. Explore 74 thoughtfully crafted themes for DeepSeek Harness, from quiet neutrals to unapologetic color.',
  explore: 'Find your theme', github: 'View on GitHub',
  heroNote: 'Open source. One plugin. A whole new feeling.',
  previewLabel: 'INTERACTIVE COLOR PREVIEW', previewHint: 'Pick a palette. See the difference.',
  previewWorkspace: 'Personal workspace', previewSession: 'A fresh perspective',
  previewQuestion: 'Let’s make something worth spending time in.',
  previewAnswer: 'A little less friction. A little more focus. A space that feels entirely your own.',
  previewTask: 'A workspace, reimagined', previewTaskNote: 'Same possibilities. A different point of view.',
  previewInput: 'What would you like to create?', previewDisclaimer: 'Simulated interface · real theme colors',
  themeLoading: 'Loading theme palettes…', themeError: 'Theme palettes could not load. Check your connection and try again.', retry: 'Try again',
  stats: [['74', 'distinct themes'], ['01', 'native plugin'], ['MIT', 'open source']],
  collectionEyebrow: '01 / THE COLLECTION', collectionTitle: 'Find your everyday favorite.',
  collectionIntro: 'Familiar design languages, reinterpreted for your AI workspace. Click any theme to try its palette in the preview.',
  search: 'Search themes', searchPlaceholder: 'Find Claude, Linear, Spotify…',
  filters: ['All themes', 'Light', 'Dark'], categoryLabel: 'Category', allCategories: 'All categories',
  count: '{count} of 74 themes', selected: 'Previewing', previewAction: 'Preview', light: 'Light', dark: 'Dark',
  emptyTitle: 'No theme found. Yet.', emptyText: 'Try a different name or give the filters a fresh start.', reset: 'Clear filters',
  showAll: 'Explore all 74 themes', showLess: 'Show fewer themes', backPreview: 'View selected palette ↑',
  nativeEyebrow: '02 / NATIVE BY DESIGN', nativeTitle: 'A new look.<br>The same Harness.',
  nativeIntro: 'Built on the idea that everything is a plugin. Your theme belongs in your workspace, right alongside the tools you already use.',
  features: [
    ['Fits right in.', 'Registers through Harness’s public Theme Service and adds its own section in Settings. Everything is where you expect it.'],
    ['Make it yours. Keep it yours.', 'Choose once and carry on. Your selected theme stays active after a reload, in the plugin’s own settings namespace.'],
    ['Small footprint. Full expression.', 'Installed through the native plugin manager. No edits to Harness source code, no replacement files, no extra browser extension.'],
  ],
  blog: 'Read the story: Everything is a Plugin',
  installEyebrow: '03 / MAKE YOURSELF AT HOME', installTitle: 'One command away<br>from a fresh start.',
  installIntro: 'Already using DeepSeek Harness? Add the plugin, launch the web app, and pick your favorite.',
  stepInstall: 'Add the plugin', stepLaunch: 'Launch Harness', stepChoose: 'Choose your theme',
  chooseText: 'Open Settings → Design MD themes. Select a card. Make yourself at home.',
  copy: 'Copy', copied: 'Copied!', copyFallback: 'Select and copy the command below.', commandLabel: 'Install command',
  compatibility: 'Compatibility documented for DeepSeek Harness 0.1.1-rc.2. Build requirements: Node.js ^22.19.0 or ≥24.0.0.',
  installDocs: 'Installation guide', faqTitle: 'A few things to know.',
  faqs: [
    ['Does this change my Harness installation?', 'The plugin uses Harness’s public extension services. It registers themes and a settings section without modifying Harness source files.'],
    ['Does choosing a theme here change my app?', 'This page is an interactive color preview. To apply a theme in your own Harness app, install the plugin and choose it in Settings → Design MD themes.'],
    ['Where do the 74 themes come from?', 'They are generated from a pinned snapshot of VoltAgent’s awesome-design-md collection, with colors normalized into Harness theme tokens. The names identify design inspiration, not official partnerships.'],
    ['Is it free to use?', 'Yes. This project is open source under the MIT license. See the repository for the license, source attribution, and third-party notices.'],
  ],
  footerTitle: 'Yours, by design.', footerNote: 'An independent theme collection for DeepSeek Harness.',
  attribution: 'Inspired by VoltAgent / awesome-design-md. Brand names identify style inspiration; no affiliation or endorsement is implied.',
  source: 'Source code', license: 'MIT license', notices: 'Attribution',
  noScript: 'Enable JavaScript for the interactive theme collection. Installation instructions and links remain available below.',
}
